/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pet.glb --transform 
Files: public/models/pet.glb [44.51MB] > D:\cuddle paw\pet-transformed.glb [4.73MB] (89%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/pet-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Rover">
          <group name="Geometry">
            <group name="Rover_Props">
              <skinnedMesh name="Rover_travel_bag" geometry={nodes.Rover_travel_bag.geometry} material={materials.material1} skeleton={nodes.Rover_travel_bag.skeleton} />
              <skinnedMesh name="Rover_footprint" geometry={nodes.Rover_footprint.geometry} material={materials.material1} skeleton={nodes.Rover_footprint.skeleton} />
            </group>
            <skinnedMesh name="Rover_1" geometry={nodes.Rover_1.geometry} material={materials.material0} skeleton={nodes.Rover_1.skeleton} />
          </group>
          <primitive object={nodes.Rover_Skeleton} />
        </group>
        <group name="Grass_lawn" position={[0, -0.148, -2.266]} scale={[629.877, 396.205, 396.205]}>
          <group name="RootNode0" scale={0.01}>
            <group name="diorama_21">
              <mesh name="node2" geometry={nodes.node2.geometry} material={materials.material0} />
              <mesh name="node3" geometry={nodes.node3.geometry} material={materials.material1} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pet-transformed.glb')
